### PR TITLE
Remove repgen install

### PR DESCRIPTION
**Pull request by mhines-usgs**
Just leave behind setup of R, Rserve, pandoc, gsplot to become the docker-aqcu-rserve base

### CODE REVIEW

**Comment by isuftin** [comment]
So do you know if this rserve is supposed to still run without the repgen installed? Travis seems to think it is running but what have you seen locally?

**Comment by mhines-usgs** [comment]
I'll paste what happens when it finishes. :zzz:

**Comment by isuftin** [comment]
If you can achieve a "healthy" status here, you should be good to merge. How do you feel about splitting up repgen and gsplot with gsplot ending up in this base container?

**Comment by mhines-usgs** [comment]
I feel fine about it, it seems to make sense to me since that is very much less likely to change as often (as are all the other parts in the base container). But I'd appreciate @zmoore-usgs input too.

**Comment by mhines-usgs** [comment]
Here are the last few lines of the docker-compose up

**Comment by mhines-usgs** [comment]
Last few lines of docker-compose up on this container
```
Removing intermediate container 6a23351a72f5
 ---> 921cf96f0d4c
Step 23/26 : EXPOSE 6311
 ---> Running in 8a666cf12cb7
Removing intermediate container 8a666cf12cb7
 ---> 4b2caf8b259c
Step 24/26 : HEALTHCHECK --interval=2s --timeout=3s  CMD sleep 1 |  		telnet localhost 6311 | 		grep -q Rsrv0103QAP1 || exit 1
 ---> Running in 90a0131ea8e4
Removing intermediate container 90a0131ea8e4
 ---> d5dc489461a9
Step 25/26 : USER root
 ---> Running in 1d4a58b057cf
Removing intermediate container 1d4a58b057cf
 ---> 8ebeb6c8996f
Step 26/26 : CMD ["/opt/rserve/bin/run_rserve.sh"]
 ---> Running in 7ff3f1fdc202
Removing intermediate container 7ff3f1fdc202
 ---> a1cefc527b80
```

docker ps shows
```
megan@megan-VirtualBox:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                    PORTS                    NAMES
b75344fa7438        aqcu-rserve:0.0.1   "/opt/rserve/bin/run…"   29 seconds ago      Up 28 seconds (healthy)   0.0.0.0:6311->6311/tcp   docker-aqcu-rserve_rserve_1
```

When i get into the container I can see what is expected for the gsplot install (imports section here plus those package's upstream dependencies https://github.com/USGS-R/gsplot/blob/master/DESCRIPTION)
```
megan@megan-VirtualBox:~$ docker exec -it b75344 /bin/bash
root@b75344fa7438:/# ls
bin   dev  home  lib32	libx32	mnt  proc  run	 srv  tmp  var
boot  etc  lib	 lib64	media	opt  root  sbin  sys  usr
root@b75344fa7438:/# cd opt
root@b75344fa7438:/opt# ls
rserve
root@b75344fa7438:/opt# cd rserve
root@b75344fa7438:/opt/rserve# ls
bin  etc  R_libs  work
root@b75344fa7438:/opt/rserve# cd R_libs/
root@b75344fa7438:/opt/rserve/R_libs# ls
curl	  git2r   jsonlite  memoise  R6		 withr
devtools  gsplot  lazyeval  mime     rstudioapi  yaml
digest	  httr	  magrittr  openssl  whisker
root@b75344fa7438:/opt/rserve/R_libs# 
```

**Comment by mhines-usgs** [comment]
I don't understand what that healthcheck is supposed to return though, and if that's healthy or not.

**Comment by isuftin** [comment]
It seems like the health check is coming back normal since your output of `docker ps` shows healthy. The `Rsrv0103QAPI` is a string that rserve sends back on a successful network connection as a way of identifying itself to the client.

**Comment by mhines-usgs** [comment]
@isuftin awesome, glad to hear this is normal

**Comment by isuftin** [comment]
Go for merge

**Pull request merged**
